# Generated by Django 5.1.3 on 2024-11-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_imagepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepair',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagepair',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
